<div class="container ">
    <img src="img/aboutBass.png" class="pull-left" style="padding: 20px;">
    <h1 class="page-header">About Thor Instruments<br/>
    <small>Every bass and guitar is one of a kind.</small></h1>
    <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent bibendum, magna et fermentum convallis, ipsum justo scelerisque velit, vel lobortis quam risus eu est. Etiam sed enim vel lorem sodales placerat. Fusce tincidunt leo sit amet elit lacinia blandit. Sed ornare nunc vitae leo pellentesque eu interdum est aliquet. Proin nec nibh arcu, vel varius ligula. Pellentesque consequat commodo sapien, et placerat nisi laoreet sit amet. Donec fringilla, lacus eget varius gravida, arcu dolor euismod nulla, non mattis elit erat non felis. Maecenas volutpat enim egestas magna sollicitudin sed interdum lacus volutpat. Morbi dictum posuere bibendum. Donec consectetur facilisis rhoncus. Sed convallis rhoncus metus et ornare. Maecenas semper luctus risus sit amet blandit. Praesent tortor sem, imperdiet quis luctus ac, vestibulum quis felis. Cras eget magna id massa mollis elementum.</p>

    <p>Fusce ultrices purus non neque vestibulum tempus. Phasellus in mi in mi vestibulum ultrices. Aliquam turpis eros, convallis et condimentum at, volutpat non lacus. Donec tincidunt vestibulum quam, at malesuada eros cursus at. Cras rhoncus nibh sit amet enim elementum viverra. Proin a mi quis tellus adipiscing aliquam eu id felis. Integer a nunc massa, eu placerat massa. Integer metus neque, commodo ut rutrum sed, molestie non mi. Curabitur eu porttitor mi. In et justo tellus, a scelerisque arcu. Praesent at nulla sapien. Proin blandit ultrices erat sit amet convallis. Etiam molestie blandit dapibus. Phasellus ac diam sem, ornare interdum arcu. Nam malesuada lectus ut risus rhoncus molestie. Sed gravida blandit fringilla.</p>

    <p>Pellentesque malesuada dictum urna, at vulputate massa molestie vel. Praesent in sapien mollis ante aliquet tincidunt. Etiam mauris lorem, dapibus quis varius non, aliquet a arcu. Sed aliquet malesuada ante, ac laoreet neque luctus et. Pellentesque non ipsum purus. Pellentesque aliquet, ligula in euismod molestie, quam felis cursus dui, sed tempus nulla leo rhoncus felis. Donec gravida libero ullamcorper augue aliquam pretium. Ut facilisis ornare malesuada. Sed velit nunc, molestie non imperdiet vitae, consequat vel nisl. Donec rhoncus auctor aliquet. In hac habitasse platea dictumst.</p>

    <p>Sed quis tellus lorem, aliquam tristique odio. Aenean sed congue mi. Integer non eleifend leo. Aenean nibh diam, sodales non iaculis sit amet, ullamcorper tempus ipsum. Aenean nec nibh sed sapien ultricies dictum. Vivamus id elit est, a eleifend ipsum. Phasellus blandit gravida magna, sit amet elementum massa rhoncus sed. Vivamus viverra suscipit ligula mollis ultricies. Donec ac est metus, ut vestibulum metus. Etiam quis leo neque, sit amet malesuada quam. Duis interdum sodales sapien imperdiet faucibus.</p>

    <p>Donec vitae sollicitudin arcu. Duis justo mauris, auctor vitae pulvinar quis, mollis at mi. Aliquam viverra, ipsum vel dapibus sodales, sem enim sollicitudin tellus, sit amet dapibus diam erat commodo ligula. Integer nec feugiat velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis mauris turpis, congue vel volutpat in, elementum eget velit. In metus sem, posuere et lobortis sed, dignissim in enim. Nam scelerisque consequat volutpat. Sed ligula nunc, interdum nec consectetur hendrerit, pellentesque eget ligula.</p>

    <h4 class="pull-right" style="margin-right: 50px;">
        <small>Signed,</small><br>
        Karl Thorkildsen<br></h4>
</div>