<div class="container">
    <h1 class="page-header">Materials<br/>
        <small>Present the appearance, attributes, and uses of woods available.</small></h1>
    <div class="row">
        <div class="span3"><img src="/img/materials/AlmondOak.jpg" alt="Almond Oak" class="img-rounded" style="margin-top: 20px; border: 1px #000 solid;"></div>
        <div class="thumbnailCaption"><h3>Almond Oak</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin elit turpis, hendrerit ut venenatis vitae, cursus id ligula. Fusce vestibulum risus in sem dapibus scelerisque porttitor odio mattis. Praesent neque lorem, aliquam et accumsan sit amet, volutpat in ligula. Aenean elit metus, egestas vel vulputate quis, fermentum quis turpis. Duis interdum diam vel metus condimentum vel pretium diam tristique. In nec risus dui. Nunc laoreet, ante a egestas imperdiet, arcu sapien venenatis velit, hendrerit pellentesque enim velit nec massa. Pellentesque ut hendrerit ligula. Aliquam non ipsum magna, at pulvinar lacus. Nulla sed tortor vel nulla porttitor posuere. Quisque adipiscing elit eu nibh fringilla ac tempus dui laoreet. Nullam ipsum nisl, lobortis non sollicitudin vel, laoreet eget diam. Praesent nec enim in nulla mattis egestas ut sed nunc. Nulla sit amet lectus at dui luctus mollis in sed felis.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin elit turpis, hendrerit ut venenatis vitae, cursus id ligula. Fusce vestibulum risus in sem dapibus scelerisque porttitor odio mattis. Praesent neque lorem, aliquam et accumsan sit amet, volutpat in ligula. Aenean elit metus, egestas vel vulputate quis, fermentum quis turpis. Duis interdum diam vel metus condimentum vel pretium diam tristique. In nec risus dui. Nunc laoreet, ante a egestas imperdiet, arcu sapien venenatis velit, hendrerit pellentesque enim velit nec massa. Pellentesque ut hendrerit ligula. Aliquam non ipsum magna, at pulvinar lacus. Nulla sed tortor vel nulla porttitor posuere. Quisque adipiscing elit eu nibh fringilla ac tempus dui laoreet. Nullam ipsum nisl, lobortis non sollicitudin vel, laoreet eget diam. Praesent nec enim in nulla mattis egestas ut sed nunc. Nulla sit amet lectus at dui luctus mollis in sed felis.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin elit turpis, hendrerit ut venenatis vitae, cursus id ligula. Fusce vestibulum risus in sem dapibus scelerisque porttitor odio mattis. Praesent neque lorem, aliquam et accumsan sit amet, volutpat in ligula. Aenean elit metus, egestas vel vulputate quis, fermentum quis turpis. Duis interdum diam vel metus condimentum vel pretium diam tristique. In nec risus dui. Nunc laoreet, ante a egestas imperdiet, arcu sapien venenatis velit, hendrerit pellentesque enim velit nec massa. Pellentesque ut hendrerit ligula. Aliquam non ipsum magna, at pulvinar lacus. Nulla sed tortor vel nulla porttitor posuere. Quisque adipiscing elit eu nibh fringilla ac tempus dui laoreet. Nullam ipsum nisl, lobortis non sollicitudin vel, laoreet eget diam. Praesent nec enim in nulla mattis egestas ut sed nunc. Nulla sit amet lectus at dui luctus mollis in sed felis.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin elit turpis, hendrerit ut venenatis vitae, cursus id ligula. Fusce vestibulum risus in sem dapibus scelerisque porttitor odio mattis. Praesent neque lorem, aliquam et accumsan sit amet, volutpat in ligula. Aenean elit metus, egestas vel vulputate quis, fermentum quis turpis. Duis interdum diam vel metus condimentum vel pretium diam tristique. In nec risus dui. Nunc laoreet, ante a egestas imperdiet, arcu sapien venenatis velit, hendrerit pellentesque enim velit nec massa. Pellentesque ut hendrerit ligula. Aliquam non ipsum magna, at pulvinar lacus. Nulla sed tortor vel nulla porttitor posuere. Quisque adipiscing elit eu nibh fringilla ac tempus dui laoreet. Nullam ipsum nisl, lobortis non sollicitudin vel, laoreet eget diam. Praesent nec enim in nulla mattis egestas ut sed nunc. Nulla sit amet lectus at dui luctus mollis in sed felis.</p>
            <p><a href="#" class="btn btn-primary">Learn More</a></p>
        </div>
    </div>
    <hr class="divider">
    <div class="row">
        <div class="span3"><img src="/img/materials/Apple.jpg" alt="Apple" class="img-rounded" style="margin-top: 20px; border: 1px #000 solid;"></div>
        <div class="thumbnailCaption"><h3>Apple</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin elit turpis, hendrerit ut venenatis vitae, cursus id ligula. Fusce vestibulum risus in sem dapibus scelerisque porttitor odio mattis. Praesent neque lorem, aliquam et accumsan sit amet, volutpat in ligula. Aenean elit metus, egestas vel vulputate quis, fermentum quis turpis. Duis interdum diam vel metus condimentum vel pretium diam tristique. In nec risus dui. Nunc laoreet, ante a egestas imperdiet, arcu sapien venenatis velit, hendrerit pellentesque enim velit nec massa. Pellentesque ut hendrerit ligula. Aliquam non ipsum magna, at pulvinar lacus. Nulla sed tortor vel nulla porttitor posuere. Quisque adipiscing elit eu nibh fringilla ac tempus dui laoreet. Nullam ipsum nisl, lobortis non sollicitudin vel, laoreet eget diam. Praesent nec enim in nulla mattis egestas ut sed nunc. Nulla sit amet lectus at dui luctus mollis in sed felis.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin elit turpis, hendrerit ut venenatis vitae, cursus id ligula. Fusce vestibulum risus in sem dapibus scelerisque porttitor odio mattis. Praesent neque lorem, aliquam et accumsan sit amet, volutpat in ligula. Aenean elit metus, egestas vel vulputate quis, fermentum quis turpis. Duis interdum diam vel metus condimentum vel pretium diam tristique. In nec risus dui. Nunc laoreet, ante a egestas imperdiet, arcu sapien venenatis velit, hendrerit pellentesque enim velit nec massa. Pellentesque ut hendrerit ligula. Aliquam non ipsum magna, at pulvinar lacus. Nulla sed tortor vel nulla porttitor posuere. Quisque adipiscing elit eu nibh fringilla ac tempus dui laoreet. Nullam ipsum nisl, lobortis non sollicitudin vel, laoreet eget diam. Praesent nec enim in nulla mattis egestas ut sed nunc. Nulla sit amet lectus at dui luctus mollis in sed felis.</p>
            <p><a href="#" class="btn btn-primary">Learn More</a></p>
        </div>
    </div>
    <hr class="divider">
    <div class="row">
        <div class="span3"><img src="/img/materials/Apricot.jpg" alt="Apricot" class="img-rounded" style="margin-top: 20px; border: 1px #000 solid;"></div>
        <div class="thumbnailCaption"><h3>Apricot</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin elit turpis, hendrerit ut venenatis vitae, cursus id ligula. Fusce vestibulum risus in sem dapibus scelerisque porttitor odio mattis. Praesent neque lorem, aliquam et accumsan sit amet, volutpat in ligula. Aenean elit metus, egestas vel vulputate quis, fermentum quis turpis. Duis interdum diam vel metus condimentum vel pretium diam tristique. In nec risus dui. Nunc laoreet, ante a egestas imperdiet, arcu sapien venenatis velit, hendrerit pellentesque enim velit nec massa. Pellentesque ut hendrerit ligula. Aliquam non ipsum magna, at pulvinar lacus. Nulla sed tortor vel nulla porttitor posuere. Quisque adipiscing elit eu nibh fringilla ac tempus dui laoreet. Nullam ipsum nisl, lobortis non sollicitudin vel, laoreet eget diam. Praesent nec enim in nulla mattis egestas ut sed nunc. Nulla sit amet lectus at dui luctus mollis in sed felis.</p>
            <p><a href="#" class="btn btn-primary">Learn More</a></p>
        </div>
    </div>
    <hr class="divider">
    <div class="row">
        <div class="span3"><img src="/img/materials/Oak.jpg" alt="Oak" class="img-rounded" style="margin-top: 20px; border: 1px #000 solid;"></div>
        <div class="thumbnailCaption"><h3>Oak</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin elit turpis, hendrerit ut venenatis vitae, cursus id ligula. Fusce vestibulum risus in sem dapibus scelerisque porttitor odio mattis. Praesent neque lorem, aliquam et accumsan sit amet, volutpat in ligula. Aenean elit metus, egestas vel vulputate quis, fermentum quis turpis. Duis interdum diam vel metus condimentum vel pretium diam tristique. In nec risus dui. Nunc laoreet, ante a egestas imperdiet, arcu sapien venenatis velit, hendrerit pellentesque enim velit nec massa. Pellentesque ut hendrerit ligula. Aliquam non ipsum magna, at pulvinar lacus. Nulla sed tortor vel nulla porttitor posuere. Quisque adipiscing elit eu nibh fringilla ac tempus dui laoreet. Nullam ipsum nisl, lobortis non sollicitudin vel, laoreet eget diam. Praesent nec enim in nulla mattis egestas ut sed nunc. Nulla sit amet lectus at dui luctus mollis in sed felis.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin elit turpis, hendrerit ut venenatis vitae, cursus id ligula. Fusce vestibulum risus in sem dapibus scelerisque porttitor odio mattis. Praesent neque lorem, aliquam et accumsan sit amet, volutpat in ligula. Aenean elit metus, egestas vel vulputate quis, fermentum quis turpis. Duis interdum diam vel metus condimentum vel pretium diam tristique. In nec risus dui. Nunc laoreet, ante a egestas imperdiet, arcu sapien venenatis velit, hendrerit pellentesque enim velit nec massa. Pellentesque ut hendrerit ligula. Aliquam non ipsum magna, at pulvinar lacus. Nulla sed tortor vel nulla porttitor posuere. Quisque adipiscing elit eu nibh fringilla ac tempus dui laoreet. Nullam ipsum nisl, lobortis non sollicitudin vel, laoreet eget diam. Praesent nec enim in nulla mattis egestas ut sed nunc. Nulla sit amet lectus at dui luctus mollis in sed felis.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin elit turpis, hendrerit ut venenatis vitae, cursus id ligula. Fusce vestibulum risus in sem dapibus scelerisque porttitor odio mattis. Praesent neque lorem, aliquam et accumsan sit amet, volutpat in ligula. Aenean elit metus, egestas vel vulputate quis, fermentum quis turpis. Duis interdum diam vel metus condimentum vel pretium diam tristique. In nec risus dui. Nunc laoreet, ante a egestas imperdiet, arcu sapien venenatis velit, hendrerit pellentesque enim velit nec massa. Pellentesque ut hendrerit ligula. Aliquam non ipsum magna, at pulvinar lacus. Nulla sed tortor vel nulla porttitor posuere. Quisque adipiscing elit eu nibh fringilla ac tempus dui laoreet. Nullam ipsum nisl, lobortis non sollicitudin vel, laoreet eget diam. Praesent nec enim in nulla mattis egestas ut sed nunc. Nulla sit amet lectus at dui luctus mollis in sed felis.</p>
            <p><a href="#" class="btn btn-primary">Learn More</a></p>
        </div>
    </div>
    <hr class="divider">
    <div class="row">
        <div class="span3"><img src="/img/materials/Beech.jpg" alt="Beech" class="img-rounded" style="margin-top: 20px; border: 1px #000 solid;"></div>
        <div class="thumbnailCaption"><h3>Beech</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin elit turpis, hendrerit ut venenatis vitae, cursus id ligula. Fusce vestibulum risus in sem dapibus scelerisque porttitor odio mattis. Praesent neque lorem, aliquam et accumsan sit amet, volutpat in ligula. Aenean elit metus, egestas vel vulputate quis, fermentum quis turpis. Duis interdum diam vel metus condimentum vel pretium diam tristique. In nec risus dui. Nunc laoreet, ante a egestas imperdiet, arcu sapien venenatis velit, hendrerit pellentesque enim velit nec massa. Pellentesque ut hendrerit ligula. Aliquam non ipsum magna, at pulvinar lacus. Nulla sed tortor vel nulla porttitor posuere. Quisque adipiscing elit eu nibh fringilla ac tempus dui laoreet. Nullam ipsum nisl, lobortis non sollicitudin vel, laoreet eget diam. Praesent nec enim in nulla mattis egestas ut sed nunc. Nulla sit amet lectus at dui luctus mollis in sed felis.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin elit turpis, hendrerit ut venenatis vitae, cursus id ligula. Fusce vestibulum risus in sem dapibus scelerisque porttitor odio mattis. Praesent neque lorem, aliquam et accumsan sit amet, volutpat in ligula. Aenean elit metus, egestas vel vulputate quis, fermentum quis turpis. Duis interdum diam vel metus condimentum vel pretium diam tristique. In nec risus dui. Nunc laoreet, ante a egestas imperdiet, arcu sapien venenatis velit, hendrerit pellentesque enim velit nec massa. Pellentesque ut hendrerit ligula. Aliquam non ipsum magna, at pulvinar lacus. Nulla sed tortor vel nulla porttitor posuere. Quisque adipiscing elit eu nibh fringilla ac tempus dui laoreet. Nullam ipsum nisl, lobortis non sollicitudin vel, laoreet eget diam. Praesent nec enim in nulla mattis egestas ut sed nunc. Nulla sit amet lectus at dui luctus mollis in sed felis.</p>
            <p><a href="#" class="btn btn-primary">Learn More</a></p>
        </div>
    </div>
    <h6 class="pull-right">All wood grain images obtained with permission from <a href="http://www.wood-database.com/wood-identification/" target="_blank">The Wood Database</a>.</h6>
</div>